{
  "openapi": "3.0.0",
  "info": {
    "title": "Challange 05 Nodejs Rocketseat Ignite",
    "description": "This is an API challenge 05",
    "version": "1.0.0",
    "contact": {
      "email": "renansx2013@hotmail.com"
    }
  },
  "paths": {
    "/users": {
      "post": {
        "tags": ["User"],
        "summary": "Create user",
        "description": "Create a new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "john Doe",
                  "email": "johndoe@email.com"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/user"
                },
                "example": {
                  "id": "99fd3353-0a0b-4e5a-84f1-6b7211b52f31",
                  "admin": false,
                  "name": "john Doe",
                  "email": "johndoe@email.com",
                  "created_at": "2022-07-03T01:17:38.595Z",
                  "updated_at": "2022-07-03T01:17:38.595Z"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User already exists!"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["User"],
        "summary": "List all users",
        "description": "Only admins can list all users",
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "required": true,
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/user"
                  }
                },
                "example": [{
                  "id": "99fd3353-0a0b-4e5a-84f1-6b7211b52f31",
                  "admin": false,
                  "name": "john Doe",
                  "email": "johndoe@email.com",
                  "created_at": "2022-07-03T01:17:38.595Z",
                  "updated_at": "2022-07-03T01:17:38.595Z"
                }]
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "You need to be an administrator to list all users."
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": ["User"],
        "summary": "Get an user",
        "description": "Get an user",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/user"
                },
                "example": {
                  "id": "99fd3353-0a0b-4e5a-84f1-6b7211b52f31",
                  "admin": false,
                  "name": "john Doe",
                  "email": "johndoe@email.com",
                  "created_at": "2022-07-03T01:17:38.595Z",
                  "updated_at": "2022-07-03T01:17:38.595Z"
                }
              }
            }
          },
          "404": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User not found!"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["User"],
        "summary": "Update admin property",
        "description": "Update admin property",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true,
            "description": "User id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "admin": {
                    "type": "boolean"
                  },
                  "updated_at": {
                    "type": "string"
                  }
                },
                "example": {
                  "admin": true,
                  "updated_at": "2022-07-03T01:17:38.595Z"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/user"
                },
                "example": {
                  "id": "99fd3353-0a0b-4e5a-84f1-6b7211b52f31",
                  "admin": false,
                  "name": "john Doe",
                  "email": "johndoe@email.com",
                  "created_at": "2022-07-03T01:17:38.595Z",
                  "updated_at": "2022-07-03T01:17:38.595Z"
                }
              }
            }
          },
          "404": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User not found!"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "user": {
      "schema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      }
    }
  }
}